config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHomeView.as_view(), name='bucket'),
    path('object/delete/<path:key>', views.BucketObjectDeleteView.as_view(), name='bucket_object_delete'),
    path('object/download/<path:key>', views.BucketObjectDownloadView.as_view(), name='bucket_object_download'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('categories/<slug:category_slug>', views.HomeView.as_view(), name="category"),
    path('bucket/', include(bucket_urls)),
    path('product/<slug:slug>', views.ProductDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = "orders"

payment_url = [
    path('<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
]

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name="order_create"),
    path('bill/<int:order_id>/', views.OrderBillView.as_view(), name="order_bill"),
    path('cart/', views.CartView.as_view(), name="cart"),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name="cart_add"),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name="cart_remove"),
    path('payment/', include(payment_url)),
    path('coupon/add/<int:order_id>', views.CouponAddView.as_view(), name="coupon_add")
]

home/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField


class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name="s_category", blank=True, null=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("home:category", args=[self.slug])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d/")
    description = RichTextField()
    available = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("home:product_detail", args=[self.slug])

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Product, Category
from django.shortcuts import get_object_or_404
from . import tasks
from django.contrib import messages
from utils import IsAdminUserMixin
from orders.forms import CartAddForm


class HomeView(View):
    def get(self, request, category_slug=None):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = Product.objects.filter(category=category)
        return render(request, 'home/home.html', {'products': products, 'categories': categories})


class ProductDetailView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        form = CartAddForm()
        return render(request, "home/detail.html", {'product': product, 'form': form})


class BucketHomeView(IsAdminUserMixin, View):
    template_name = 'home/bucket.html'

    def get(self, request):
        all_bucket_objects = tasks.all_bucket_objects_task()
        return render(request, self.template_name, {'objects': all_bucket_objects})


class BucketObjectDeleteView(IsAdminUserMixin, View):
    def get(self, request, key):
        tasks.delete_bucket_object_task.delay(key)
        messages.info(request, "Your object will deleted soon", "info")
        return redirect("home:bucket")


class BucketObjectDownloadView(IsAdminUserMixin, View):
    def get(self, request, key):
        tasks.download_bucket_object_task.delay(key)
        messages.info(request, "Your file will downloaded soon. check out aws folder in root of your project", "info")
        return redirect("home:bucket")

home/templates/home/bucket.html
{% extends 'base.html' %}

{% block content %}

    <h3>Bucket</h3><br>

    <table class="table table-bordered table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Object Name</th>
            <th scope="col">Size</th>
            <th scope="col">Download</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in objects %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ obj.Key }}</td>
                <td>{{ obj.Size|filesizeformat }}</td>
                <td><a class="btn btn-primary" href="{% url 'home:bucket_object_download' obj.Key %}">download</a></td>
                <td><a class="btn btn-danger" href="{% url 'home:bucket_object_delete' obj.Key %}">delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}

    <h3>{{ product.name }}</h3>
    <smal>{{ product.created }}</smal><br><br>

    <img src="{{ product.image.url }}" style="max-width:20%;" alt="product"><br><br>

    <h6>{{ product.description|safe }}</h6>

    <h4>Price : <strong>{{ product.price }}</strong> $ </h4><br><br>

    <form action="{% url 'orders:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add to Cart">

    </form>

{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'home/css/home_style.css' %}">
{% endblock %}

{% block content %}

    <div class="container">

        <div class="row">

            <div class="col-md-10">

                <a href="{% url 'home:home' %}" class="btn btn-danger">All</a>
                <!-- Example split danger button -->
                {% for category in categories %}
                    <div class="btn-group">
                        <a href="{{ category.get_absolute_url }}" class="btn btn-info">{{ category.name }}</a>
                        <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu">

                            {% for sub in category.s_category.all %}

                                <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>

                            {% endfor %}

                        </ul>
                    </div>
                {% endfor %}


            </div>


        </div>

        <br><br>

        <div class="row">


            {% for product in products %}
                <div class="col-md-3">

                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ product.price }} $ </h6>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-primary">See More</a>
                        </div>
                    </div>

                </div>
            {% endfor %}


        </div>

    </div>



{% endblock %}