config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHomeView.as_view(), name='bucket'),
    path('object/delete/<path:key>', views.BucketObjectDeleteView.as_view(), name='bucket_object_delete'),
    path('object/download/<path:key>', views.BucketObjectDownloadView.as_view(), name='bucket_object_download'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('categories/<slug:category_slug>', views.HomeView.as_view(), name="category"),
    path('bucket/', include(bucket_urls)),
    path('product/<slug:slug>', views.ProductDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = "orders"

payment_url = [
    path('<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
]

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name="order_create"),
    path('bill/<int:order_id>/', views.OrderBillView.as_view(), name="order_bill"),
    path('cart/', views.CartView.as_view(), name="cart"),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name="cart_add"),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name="cart_remove"),
    path('payment/', include(payment_url)),
    path('coupon/add/<int:order_id>', views.CouponAddView.as_view(), name="coupon_add")
]

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from home.models import Product
from django.core.validators import MinValueValidator, MaxValueValidator


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.IntegerField(blank=True, null=True, default=None)

    class Meta:
        ordering = ('paid', '-updated')

    def __str__(self):
        return f'{self.user} - {str(self.id)}'

    def get_total_price(self):
        total = sum(item.get_product_cost() for item in self.items.all())
        if self.discount:
            discount_price = (total / 100) * self.discount
            return total - discount_price
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_product_cost(self):
        return self.price * self.quantity


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(90)])
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.code

orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9)


class CouponAddForm(forms.Form):
    code = forms.CharField(max_length=30)

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .cart import Cart
from home.models import Product
from .forms import CartAddForm, CouponAddForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order, OrderItem, Coupon
from datetime import datetime


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, "orders/cart.html", {'cart': cart})


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        messages.success(request, "Product Successfully Added to Card", "success")
        return redirect('home:product_detail', product.slug)


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product.id)
        return redirect("orders:cart")


class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user)
        if not len(cart):
            messages.error(request, "No Item to buy! Cart is empty", 'danger')
            return redirect("orders:cart")
        for item in cart:
            order_item = OrderItem.objects.create(order=order, product=item['name'], price=item['price'],
                                                  quantity=item['quantity'])
        cart.clear()
        return redirect('orders:order_bill', order.id)


class OrderBillView(LoginRequiredMixin, View):
    form_class = CouponAddForm

    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        # save order id in session to use it when verifying
        request.session['order_pay'] = {
            'order_id': order.id
        }
        return render(request, "orders/bill.html", {'order': order, 'form': self.form_class})


class CouponAddView(LoginRequiredMixin, View):
    form_class = CouponAddForm

    def post(self, request, order_id):
        now = datetime.now()
        form = self.form_class(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            # check code validation
            try:
                coupon = Coupon.objects.get(code__exact=code, valid_from__lte=now, valid_to__gte=now, active=True)
            except Coupon.DoesNotExist:
                messages.error(request, 'coupon dose not valid', 'danger')
                return redirect('orders:order_bill', order_id)
            # add discount to order
            order = Order.objects.get(id=order_id)
            order.discount = coupon.discount
            order.save()
            # remove coupon
            coupon.delete()
        return redirect('orders:order_bill', order_id)


class OrderPayView(LoginRequiredMixin, View):
    """
    in real payment gateway this method redirect
    user to payment page
    see like below for zarinpal payment example:
    https://github.com/rasooll/zarinpal-django-py3
    """

    def get(self, request, order_id):
        # TODO: use zarinpal sandbox instead
        order = get_object_or_404(Order, id=order_id)
        return render(request, 'orders/payment.html', {'order': order})


class OrderVerifyView(LoginRequiredMixin, View):
    def get(self, request):
        order_id = request.session['order_pay']['order_id']
        order = get_object_or_404(Order, id=int(order_id))
        order.paid = True
        order.save()
        messages.success(request, "Successful payment", "success")
        return redirect("home:home")

orders/templates/orders/bill.html
{% extends 'base.html' %}


{% block content %}

    <h3>Bill</h3><br>

    <table class="table table-bordered">

        <tbody>
        <tr>
            <th scope="row">Name</th>
            <td>{{ order.user.full_name }}</td>

        </tr>
        <tr>
            <th scope="row">Email</th>
            <td>{{ order.user.email }}</td>

        </tr>
        <tr>
            <th scope="row">Phone</th>
            <td>{{ order.user.phone_number }}</td>

        </tr>
        <tr>
            <th scope="row">Submit Date</th>
            <td>{{ order.created|date }}</td>

        </tr>
        <tr>
            <th scope="row">Discount</th>
            {% if order.discount %}

                <td>{{ order.discount }} %</td>

            {% else %}

                <td> -- </td>

            {% endif %}

        </tr>
        <tr>
            <th scope="row">Final Price</th>
            <td>{{ order.get_total_price|floatformat }}</td>

        </tr>
        </tbody>
    </table><br>

    <form action="{% url 'orders:coupon_add' order.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Coupon">
    </form><br>

    <a href="{% url 'orders:order_pay' order.id %}" class="btn btn-primary">Pay</a>

{% endblock %}

orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block content %}

    <table class="table table-bordered table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Total Price</th>
            <th scope="col">Remove</th>
        </tr>
        </thead>
        <tbody>

        {% for item in cart %}

            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
                <td><a href="{% url 'orders:cart_remove' item.name.id %}" class="btn btn-danger">Remove</a></td>
            </tr>

        {% endfor %}

        <!-- total price -->
        <td>Total</td>
        <td>{{ cart.get_total_price }}</td>
        <td colspan="4"></td>

        </tbody>
    </table>

    <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>

{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}


{% block content %}

{% endblock %}

orders/templates/orders/payment.html
<!doctype html>
<html>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>Snippet - BBBootstrap</title>
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css' rel='stylesheet'>
    <link href='https://use.fontawesome.com/releases/v5.7.2/css/all.css' rel='stylesheet'>
    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <style>::-webkit-scrollbar {
        width: 8px;
    }

    /* Track */
    ::-webkit-scrollbar-track {
        background: #f1f1f1;
    }

    /* Handle */
    ::-webkit-scrollbar-thumb {
        background: #888;
    }

    /* Handle on hover */
    ::-webkit-scrollbar-thumb:hover {
        background: #555;
    }

    @import url('https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap');

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Montserrat', sans-serif;
    }

    body {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background-color: #0C4160;

        padding: 30px 10px;
    }

    .card {
        max-width: 500px;
        margin: auto;
        color: black;
        border-radius: 20px;
    }

    p {
        margin: 0px;
    }

    .container .h8 {
        font-size: 30px;
        font-weight: 800;
        text-align: center;
    }

    .btn.btn-primary {
        width: 100%;
        height: 70px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0 15px;
        background-image: linear-gradient(to right, #77A1D3 0%, #79CBCA 51%, #77A1D3 100%);
        border: none;
        transition: 0.5s;
        background-size: 200% auto;

    }


    .btn.btn.btn-primary:hover {
        background-position: right center;
        color: #fff;
        text-decoration: none;
    }


    .btn.btn-primary:hover .fas.fa-arrow-right {
        transform: translate(15px);
        transition: transform 0.2s ease-in;
    }

    .form-control {
        color: white;
        background-color: #223C60;
        border: 2px solid transparent;
        height: 60px;
        padding-left: 20px;
        vertical-align: middle;
    }

    .form-control:focus {
        color: white;
        background-color: #0C4160;
        border: 2px solid #2d4dda;
        box-shadow: none;
    }

    .text {
        font-size: 14px;
        font-weight: 600;
    }

    ::placeholder {
        font-size: 14px;
        font-weight: 600;
    }</style>
</head>
<body className='snippet-body'>
<div class="container p-0">
    <div class="card px-4">
        <p class="h8 py-3">Fake Payment Gateway</p>
        <div class="row gx-3">
            <div class="col-12">
                <div class="d-flex flex-column">
                    <p class="text mb-1">Card Number</p>
                    <input class="form-control mb-3" type="text" placeholder="1234 5678 435678">
                </div>
            </div>
            <div class="col-6">
                <div class="d-flex flex-column">
                    <p class="text mb-1">Expiry</p>
                    <input class="form-control mb-3" type="text" placeholder="MM/YYYY">
                </div>
            </div>
            <div class="col-6">
                <div class="d-flex flex-column">
                    <p class="text mb-1">CVV/CVC</p>
                    <input class="form-control mb-3 pt-2 " type="password" placeholder="***">
                </div>
            </div>
            <div class="col-12">
                <a href="{% url 'orders:order_verify' %}">
                    <div class="btn btn-primary mb-3">
                        <span class="ps-3">Pay ${{ order.get_total_price|floatformat }}</span>
                        <span class="fas fa-arrow-right"></span>
                    </div>
                </a>

            </div>
        </div>
    </div>
</div>
<script type='text/javascript'
        src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js'></script>
<script type='text/javascript' src='#'></script>
<script type='text/javascript' src='#'></script>
<script type='text/javascript' src='#'></script>
<script type='text/javascript'>#</script>
<script type='text/javascript'>var myLink = document.querySelector('a[href="#"]');
myLink.addEventListener('click', function (e) {
    e.preventDefault();
});</script>

</body>
</html>