accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('rgister/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHomeView.as_view(), name='bucket'),
    path('object/delete/<path:key>', views.BucketObjectDeleteView.as_view(), name='bucket_object_delete'),
    path('object/download/<path:key>', views.BucketObjectDownloadView.as_view(), name='bucket_object_download'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('categories/<slug:category_slug>', views.HomeView.as_view(), name="category"),
    path('bucket/', include(bucket_urls)),
    path('product/<slug:slug>', views.ProductDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = "orders"

payment_url = [
    path('<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
]

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name="order_create"),
    path('bill/<int:order_id>/', views.OrderBillView.as_view(), name="order_bill"),
    path('cart/', views.CartView.as_view(), name="cart"),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name="cart_add"),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name="cart_remove"),
    path('payment/', include(payment_url)),
    path('coupon/add/<int:order_id>', views.CouponAddView.as_view(), name="coupon_add")
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
            {% if request.user.is_authenticated %}
                <a class="nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
                <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
                <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
            {% if request.user.is_superuser %}
                <a class="nav-link active" href="{% url 'home:bucket' %}">My Bucket</a>

            {% endif %}
        </div>

        <!-- admin welcome -->
        {% if request.user.is_admin %}

            <div class="ms-auto mb-2 mb-lg-0">
                <a href="{% url 'admin:index' %}">
                    <span class="navbar-text ">
                        Admin Panel
                    </span>
                </a>

            </div>

        {% endif %}

        <!-- shop cart -->


        <a class="nav-link text-white" href="{% url 'orders:cart' %}">
            <i class="fa badge fa-lg" value={{ item_counter|length }}>&#xf07a;</i>
        </a>


    </div>
</nav>